// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package pgmodel

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type gooseDbVersionTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *gooseDbVersionTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("goose_db_version").
func (v *gooseDbVersionTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *gooseDbVersionTableType) Columns() []string {
	return []string{
		"id",
		"version_id",
		"is_applied",
		"tstamp",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *gooseDbVersionTableType) NewStruct() reform.Struct {
	return new(GooseDbVersion)
}

// NewRecord makes a new record for that table.
func (v *gooseDbVersionTableType) NewRecord() reform.Record {
	return new(GooseDbVersion)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *gooseDbVersionTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// GooseDbVersionTable represents goose_db_version view or table in SQL database.
var GooseDbVersionTable = &gooseDbVersionTableType{
	s: parse.StructInfo{
		Type:    "GooseDbVersion",
		SQLName: "goose_db_version",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "VersionID", Type: "int64", Column: "version_id"},
			{Name: "IsApplied", Type: "bool", Column: "is_applied"},
			{Name: "Tstamp", Type: "[]uint8", Column: "tstamp"},
		},
		PKFieldIndex: 0,
	},
	z: new(GooseDbVersion).Values(),
}

// String returns a string representation of this struct or record.
func (s GooseDbVersion) String() string {
	res := make([]string, 4)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "VersionID: " + reform.Inspect(s.VersionID, true)
	res[2] = "IsApplied: " + reform.Inspect(s.IsApplied, true)
	res[3] = "Tstamp: " + reform.Inspect(s.Tstamp, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *GooseDbVersion) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.VersionID,
		s.IsApplied,
		s.Tstamp,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *GooseDbVersion) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.VersionID,
		&s.IsApplied,
		&s.Tstamp,
	}
}

// View returns View object for that struct.
func (s *GooseDbVersion) View() reform.View {
	return GooseDbVersionTable
}

// Table returns Table object for that record.
func (s *GooseDbVersion) Table() reform.Table {
	return GooseDbVersionTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *GooseDbVersion) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *GooseDbVersion) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *GooseDbVersion) HasPK() bool {
	return s.ID != GooseDbVersionTable.z[GooseDbVersionTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *GooseDbVersion) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = GooseDbVersionTable
	_ reform.Struct = (*GooseDbVersion)(nil)
	_ reform.Table  = GooseDbVersionTable
	_ reform.Record = (*GooseDbVersion)(nil)
	_ fmt.Stringer  = (*GooseDbVersion)(nil)
)

func init() {
	parse.AssertUpToDate(&GooseDbVersionTable.s, new(GooseDbVersion))
}
