name: linter

on:
  push:
    branches: ["*"]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: latest